### ISSUE TITLE
A corresponding script for Linux

### ISSUE THREAD

**Issue by linux-lukas** [tbs1-bo/ita-software#1]
In view of the fact that young people may also have Linux as a private and/or business use, it would perhaps be useful to provide a script with the help of which you can install the necessary programs for Linux. That would be interesting then not only for pupils, but also for other young people.

In addition, it could perhaps be supplemented with a variety of free software, such as VS Codium, DBeaver, KeePassXC, Arduino IDE or OBS Studio.

**Comment by pintman** [comment]
Gute Idee. Erstelle gerne einen PR, den wir integrieren können.

**Comment by linux-lukas** [comment]
Script is ready. Pull request is in the making.
